/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.xtext.example.mydsl.ui.document.MyDslExpressionDocument;
import org.xtext.example.mydsl.ui.document.MyDslExpressionDocumentProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends org.xtext.example.mydsl.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
//	public com.google.inject.Provider<org.eclipse.xtext.ui.editor.model.XtextDocumentProvider> provideXtextDocumentProvider() {
//		return MyDslExpressionDocumentProvider.getProvider();
//	}
	
	public com.google.inject.Provider<org.eclipse.xtext.ui.editor.model.XtextDocument> provideXtextDocument() {
		return MyDslExpressionDocument.getProvider();
	}
	
	// contributed by org.eclipse.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment
	public Class<? extends org.eclipse.xtext.ui.editor.model.XtextDocumentProvider> bindXtextDocumentProvider() {
		return MyDslExpressionDocumentProvider.class;
	}

}
